sonar.projectKey=HassanCHKIRROU_Mettre-en-uvre-l-int-gration-et-le-d-ploiement-continu-d-une-application-Full-Stack-front
sonar.organization=hassanchkirrou
sonar.projectName=MicroCRM Front-end

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/*.spec.ts,**/node_modules/**

sonar.javascript.lcov.reportPaths=coverage/microcrm/lcov.info